### ISSUE TITLE
Support package/publish arguments

### ISSUE THREAD

**Issue by jakobrosenberg** [felipecrs/semantic-release-vsce#260]
Would it be possible to support CLI arguments, eg. something like:
```yaml
      - name: Publish
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VSCE_PAT: ${{ secrets.PUBLISHER_TOKEN }}
          VSCE_PACKAGE_ARGS: "--baseImagesUrl https://raw.githubusercontent.com/org/repo/branch/"
```
